### ISSUE TITLE
version upgrade is not working

### ISSUE THREAD

**Issue by vrathore18** [cevoaustralia/aws-google-auth#205]
I am currently having 0.0.31 version and whenever I am trying to login I keep getting an `invalid username and password.` Others are facing the same issue. To fix I think I need to update the version now.

I tried 
1. brew update aws-google-auth (also install)
2.  pip install

I see the new version is installed but when I am checking the version aws-google-auth -V. I keep getting the same old version.
Could some please let me know how I can use the updated version? Is it something to do with the python version

**Comment by bhargavamin** [comment]
It might be because of the broken link for brew installation. I would suggest a different approach:

1. Remove the current installation using `brew uninstall aws-google-auth` or `pip uninstall aws-google-auth`
2. Clone the repo
3. CD repo dir then run `pip3 install aws_google_auth/setup.py` OR `python3 setup.py install`

This way you always do `git pull` to fetch the latest changes and apply them again using point 3.

**Comment by stevemac007** [comment]
I don't manage the brew package for the application - only push the builds to pypi.

I would suggest simply doing a `pip install aws-google-auth --upgrade`

**Comment by stevemac007** [comment]
I've confirmed that brew looks to be using the latest build now `0.0.36` - https://formulae.brew.sh/formula/aws-google-auth
